#!/bin/bash
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
echo "this script is from github"
